<a href="https://colab.research.google.com/github/HarshithaShetty27/Neural-networks/blob/main/neural_networks_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CODING NEURONS AND LAYERS

NEURON WITH 3 INPUTS

In [1]:
inputs = [1,2,3]
weights = [0.2, 0.8, -0.5]
bias = 2
outputs = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias
print(outputs)

2.3


NEURON WITH 4 INPUTS

In [2]:
inputs = [1.0,2.0,3.0,2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0
outputs = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + inputs[3]*weights[3] + bias
print(outputs)

4.8


CODING A LAYER

In [3]:
inputs = [1,2,3,2.5]
weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]

weights1 = weights[0] #LIST OF WEIGHTS ASSOCIATED WITH 1ST NEURON : W11, W12, W13, W14
weights2 = weights[1] #LIST OF WEIGHTS ASSOCIATED WITH 2ND NEURON : W21, W22, W23, W24
weights3 = weights[2] #LIST OF WEIGHTS ASSOCIATED WITH 3RD NEURON : W31, W32, W33, W34

biases = [2, 3, 0.5]

outputs = [
    #neuron 1
    inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + biases[0],
    #neuron 2
    inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] + biases[1],
    #neuron 3
    inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3] + biases[2]
]
print(outputs)

[4.8, 1.21, 2.385]


USING LOOPS

In [5]:
inputs = [1,2,3,2.5]
weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

layer_outputs=[]

for neuron_weights, neuron_bias in zip(weights,biases):
  neuron_output=0
  for neuron_input, weight in zip(inputs, neuron_weights):
    neuron_output += neuron_input*weight
  neuron_output+= neuron_bias
  layer_outputs.append(neuron_output)

print(layer_outputs)

[4.8, 1.21, 2.385]


USING NUMPY

*single neuron using numpy*

In [2]:
import numpy as np
inputs = [1,2,3,2.5]
weights = [0.2, 0.8, -0.5, 1]
bias = 2
outputs = np.dot(inputs, weights) + bias
# outputs = np.dot(weights, inputs) + bias
print(outputs)

4.8


*layers of neuron using numpy*

In [3]:
inputs = [1,2,3,2.5]
weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]
layer_outputs = np.dot(weights, inputs) + biases
print(layer_outputs)

[4.8   1.21  2.385]


LAYER OF NEURONS AND BATCH OF DATA USING NUMPY

In [5]:
inputs = [[1.0, 2.0, 3.0, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

# we cannot transpose lists in python, hence we convert weight to array

outputs = np.dot(inputs,np.array(weights).T)+biases
print(outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


2 LAYERS AND BATCH OF DATA USING NUMPY

In [6]:
import numpy as np

inputs = [[1, 2, 3, 2.5],
          [2., 5., -1., 2],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

weights2 = [[0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]

inputs_array = np.array(inputs)
weights_array = np.array(weights)
biases_array = np.array(biases)
weights2_array = np.array(weights2)
biases2_array = np.array(biases2)

layer1_OP = np.dot(inputs_array,weights_array.T) +biases_array

layer2_OP = np.dot(layer1_OP, weights2_array.T) +biases2_array

print(layer2_OP)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]
